name: Deploy
on:
    push:
        branches: [main]
        paths:
            - '.github/workflows/deploy.yml'
            - 'docker-compose.yml'
            - 'Dockerfile'
            - 'src/**'
            - 'package.json'
            - 'package-lock.json'
    workflow_dispatch:
        inputs:
            force:
                description: 'Force deploy'
                required: false
jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Generate .env.production.local
              run: echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env.production.local

            - name: Build production image
              run: docker compose build --pull

            - name: Create host directory
              run: mkdir -p data

            - name: Recreate container
              run: docker compose up -d --force-recreate

            - name: Deploy commands
              run: docker compose exec -it "$(docker compose config --services)" npm run deploy-commands
              # TODO: 변경 사항이 있을 경우에만 실행하도록 수정 (deploy-commands.ts에서 구현 필요)
