name: Deploy
on:
    push:
        branches: [main]
        paths:
            - 'docker-compose.yml'
            - 'Dockerfile'
            - 'src/**'
            - 'package.json'
            - 'package-lock.json'
    workflow_dispatch:
        inputs:
            force:
                description: 'Force deploy'
                required: false
jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Generate .env.production.local
              run: echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env.production.local
            - name: Build production image
              run: docker compose build --pull
            - name: Recreate container
              run: docker compose up -d --force-recreate
            - name: Deploy Discord Commands
              # TODO: data가 바뀌었을 때만 실행되도록 수정
              # TODO: 기존 명령어 삭제
              if: contains(github.event.head_commit.modified, 'src/commands/slash/')
              run: npm run deploy-commands
            - name: Clean up old images
              run: docker image prune -f
